apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "local-registry.fullname" . }}-ingress
  labels:
data:
  tls.crt: {{ .Files.Get "cert/registry.crt" | b64enc }}
  tls.key: {{ .Files.Get "cert/registry.key" | b64enc }}
