apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "local-registry.fullname" . }}
  labels:
    {{- include "local-registry.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "local-registry.fullname" . }}-ingress
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /v2
            backend:
              serviceName: {{ .Release.Name }}-docker-registry
              servicePort: 5000
